### PR TITLE
Draft for utilizing townys NewDayEvent for interest

### PR DESCRIPTION
**Pull request by 1ByteBit**
Just a quick and dirty draft currently. I'm not sure how to optimally test this, and I had some trouble passing organizationManager to the new class, so you'll probably have to double check that.

And it's possible to remove "extends JavaPlugin" in the new class in a couple different ways, but I'll leave how we should do it up to you. Currently I just left it due to the config checks

### CODE REVIEW

**Comment by 1ByteBit** [comment]
Actually it could be possible to leave the interest code in WorldDynamicsEngine and just have the listener activate it. Do you have any thoughts?

**Comment by thatguycy** [comment]
Hi, please see https://github.com/thatguycy/WorldDynamics-Engine/commit/06e15c4161cf2611691e46b30ef27ea1bc8fa84e and let me know if this is what you meant to accomplish?

**Comment by thatguycy** [comment]
Ignore all the stuff about the HumanManager, etc, just focus on what I did with the TownyNewDayListener.java and WorldDynamicEngine.java

**Comment by 1ByteBit** [comment]
Can confirm that was the original idea. Thank you for that

**Pull request closed without merging**
